disabled_rules:
  - nesting

included:
  - Sources
  - Tests

line_length:
  warning: 140
  error: 160
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_multiline_strings: true

reporter: "xcode"

strict: true
